# Generated by Django 5.1.4 on 2025-01-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypaginate', '0003_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='test',
            new_name='text',
        ),
    ]
